### PR TITLE
Remove git reference from install-app

### LINKED ISSUE #735: install-app from worker image requires git
if install-app with git url is used it doesn't work. It needs git command installed.

should we keep the git clone out of image building and just use COPY to get the code into image?

### PR DESCRIPTION
**Pull request by vrslev**
Before, custom app builders could install apps from Git, this prevents it. Issue was that final backend images (frappe and erpnext) didn't have Git installed. In #735 we decided that we should keep Git out of the backend image.

In this PR:
- Remove Git reference from install-app scripts, update Dockerfiles accordingly
- Update custom app guide
- Fix issue with missing sites/assets folder

Fixes #735.

### CODE REVIEW

**Comment by vrslev** [comment]
@revant Review please

File: images/nginx/install-app.sh [hunk 1]
```diff
@@ -2,15 +2,10 @@
...
 
 cd /frappe-bench
 
-if test "$BRANCH" && test "$GIT_URL"; then
-  # Clone in case not copied manually
-  git clone --depth 1 -b "$BRANCH" "$GIT_URL" "apps/$APP"
-fi
-
 # Add all not built assets
 cp -r "apps/$APP/$APP/public" "/out/assets/$APP"
```
Comment (revant) [inline images/nginx/install-app.sh:10]: If app doesn't have `public` directory? can this command not fail with non 0 exit?

**Review by revant — CHANGES_REQUESTED** [review]

File: images/nginx/install-app.sh (hunk 1 above)
Comment (vrslev) [reply images/nginx/install-app.sh:10]: https://github.com/frappe/frappe_docker/issues/735#issuecomment-1081641829

Comment (revant) [reply images/nginx/install-app.sh:10]: > Users shouldn't even try to install apps without frontend code, or I am wrong here?

Some apps may not have frontend code. If you create new app it won't have frontend code. If you do bench get-app, it'll run through the script and build no assets. Yet it goes through the yarn commands. `install-app` should not fail for such apps.

**Review by revant — APPROVED** [review]
LGTM,

merge when CI completes.
